= RISC-V RPMI Specification

RPMI (RISC-V Platform Management Interface) is an extensible messaging 
interface between Application Processors and Platform Microcontrollers for
management and control of system.

This specification is based on an earlier draft located here:
https://docs.google.com/document/d/199ar3Ddd-FlzP1FR3HOkbBf1BNvLUPvJ/edit

= Licensing

The files in this repository are licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0).  The full license
text is available at https://creativecommons.org/licenses/by/4.0/.

= Contributors
Contributors to this specification are contained in the 
link:src/contributors.adoc[contributors] file.

For instructions on how to contribute please see the 
link:CONTRIBUTING.md[CONTRIBUTING] file.

= Dependencies
The PDF built in this project uses AsciiDoctor (Ruby). For more information 
on AsciiDoctor, specification guidelines, or building locally, see the 
https://github.com/riscv/docs-dev-guide[RISC-V Documentation Developer Guide].


= Discussion Forum
Discussion on RPMI occurs on 
https://lists.riscv.org/g/tech-rpmi[RPMI mailing list].


= Dependencies
The PDF built in this project uses AsciiDoctor (Ruby). For more information
on AsciiDoctor, specification guidelines, or building locally, see the
https://github.com/riscv/docs-dev-guide[RISC-V Documentation Developer Guide].

= Build Documents
This project uses
https://git-scm.com/book/en/v2/Git-Tools-Submodules[GitHub Submodules] to
include the RISC-V
https://github.com/riscv/docs-resources[docs-resources project] to achieve a
common look and feel.

When cloning this repository for the first time, you must either use
`git clone --recurse-submodules` or execute `git submodule init` and
`git submodule update` after the clone to populate the `docs-resources`
directory. Failure to clone the submodule, will result in the PDF build
fail with an error message.

The final specification in form of PDF and HTML can be generated using
`make` command. The `makefile` internally uses asciidoctor so the packages
required by the `makefile` need to be installed on the build system using
`make install-debs` or `make install-rpms`.

[,bash]
----
git clone https://github.com/riscv-non-isa/riscv-rpmi

git submodule init && git submodule update

make
----

== Meeting Slides
- https://docs.google.com/presentation/d/1rEjHMrXNHLk5J81IvnCqLJsqCuxKWkXd_HcQCj9rZnc[Meeting - May 16, 2024]
- https://docs.google.com/presentation/d/1EsrcgUZiXf_mqt4Wcd0oiRyLw4ZIGaVMa6Ew0GZ7hoQ[Meeting - May 02, 2024]
- https://docs.google.com/presentation/d/1y7NB4d6K0I3QizoQyCqlKGd99Uoaz86Mf-TApJWQXM4[Meeting - April 18, 2024]
- https://docs.google.com/presentation/d/1iwHt_GdWhRe-I-emtfD9hLmzOUFDyvuy3CuoJ6URr6Y[Meeting - April 04, 2024]
- https://docs.google.com/presentation/d/1vlMBofYgqGmSuqNZi2Btz0S4DIovCjlYHE-7aFXxlOU[Meeting - March 21, 2024]
- https://docs.google.com/presentation/d/1MFK11Yw-bHQpLLbdwhid9Cw3zTdxnljP2dA_dkcuTUU[Meeting - February 22, 2024]
- https://docs.google.com/presentation/d/1tYr7K9u-VS7JtAZXEg7gjFLe0uVocwmBYmLrZ08639k[Meeting - January 25, 2024]
