:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

== Service Groups
An RPMI service group is a collection of RPMI services that are logically
grouped based on functionality. For example, all the voltage related services
are grouped into a voltage service group. The functionality implemented by
certain RPMI service groups may impact the architectural state of application
processors due to this each RPMI service group specifies the RISC-V privilege
levels of the application processor which can be access it. For example, the
clock service groups can be accessed from M-mode and S-mode but the HSM service
group can be only accessed from M-mode.

All RPMI service groups except the BASE service group are optional. If
the `BASE_PROBE_SERVICE_GROUP` service indicates that a service group is
implemented then the RPMI service group version must conform to the RPMI
specification version returned by the `BASE_GET_SPEC_VERSION` service.
All implemented RPMI service groups must satisfy the following requirements:

. The RPMI service group must be accessible from the RISC-V privilege
level associated with the RPMI context which includes it.
. All RPMI services of the RPMI service groups must be supported except
the dedicated notification service (`SERVICE_ID = 0x00`) which is reserved
for RPMI notification messages. A RPMI service group may implement its RPMI
services partially only if it also defines a mechanism to discover supported
RPMI services.
. The RPMI service group must implement a dedicated RPMI service with
`SERVICE_ID = 0x01` to subscribe for event notifications.

NOTE: The RPMI services listed within each RPMI service group do not have
a specific order. Additionally, the sequence in which services are defined
in the specification does not necessarily reflect the order in which they
should be invoked.

This specification defines standard RPMI service groups and RPMI services
with the provision to add more service groups as required in the future.
The RPMI specification also provides experimental service group IDs space
for development of service group until a standard service group ID is
allocated. The platform vendors can provide implementation specific RPMI
service groups. The <<table_service_groups>> table below lists all standard
RPMI service groups defined by this specification.

[#table_service_groups]
.RPMI Service Groups
[cols="2, 2, 4, 3", width=100%, align="center", options="header"]
|===
| Service Group ID
| RPMI Version (Major:Minor)
| Service Group Name
| Allowed RISC-V Privilege Levels on Application Processors

| 0x0001
| 1.0
| BASE
| M-mode, S-mode

| 0x0002
| 1.0
| SYSTEM_MSI
| M-mode, S-mode

| 0x0003
| 1.0
| SYSTEM_RESET
| M-mode

| 0x0004
| 1.0
| SYSTEM_SUSPEND
| M-mode

| 0x0005
| 1.0
| HART_STATE_MANAGEMENT
| M-mode

| 0x0006
| 1.0
| CPPC
| M-mode, S-mode

| 0x0007
| 1.0
| VOLTAGE
| M-mode, S-mode

| 0x0008
| 1.0
| CLOCK
| M-mode, S-mode

| 0x0009
| 1.0
| DEVICE_POWER
| M-mode, S-mode

| 0x000A
| 1.0
| PERFORMANCE
| M-mode, S-mode

| 0x000B
| 1.0
| MANAGEMENT_MODE
| M-mode, S-mode

| 0x000C
| 1.0
| RAS_AGENT
| M-mode, S-mode

| 0x000D
| 1.0
| REQUEST_FORWARD
| M-mode, S-mode

| 0x000E
| 2.0
| LOGGING
| M-mode, S-mode

| 0x000F - 0x7BFF
|
| _Reserved for Future Use_
|

| 0x7C00 - 0x7FFF
|
| _Experimental Service Groups_
|

| 0x8000 - 0xFFFF
|
| _Implementation Specific Service Groups_
|
|===

[discrete]
==== Common Data for Enable Notification Service (Service ID = 0x01)

The mandatory RPMI service for each service group to subscribe to event
notifications has a common Request and Response data structure. Each service
group may refer to the Request and Response data table defined below,
rather than defining the same tables in their respective sections.

[#table_common_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state. +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable.
1: Enable.
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_common_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification for the `EVENT_ID` is not supported.
!===
- Other errors <<table_error_codes>>.

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state.
----
0: Notification is disabled.
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===