:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - SYSTEM_RESET (SERVICEGROUP_ID: 0x0002)
This service group defines services for system-level reset or shutdown.

The architectural reset types that are supported by default are System Cold
Reset and System Shutdown.

System Cold Reset, also known as power-on-reset, involves power cycling the
entire system. Upon a successful system cold reset, all devices undergo power
cycling in an implementation-defined sequence similar to the initial power-on
sequence of the system.

System Shutdown results in all components/devices in the system losing power.
Currently, the application processor is the only entity that can request the
system shutdown, which means that for the platform microcontroller, it is not
necessary to categorize it as a graceful or forceful shutdown. In the case of
a shutdown request, it is implicit for the platform microcontroller that the
application processor has prepared itself for a successful shutdown.

The following table lists the services in the SYSTEM_RESET service group:

[#table_sysreset_services]
.SYSTEM_RESET Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| SYSRST_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| SYSRST_GET_ATTRIBUTES
| NORMAL_REQUEST

| 0x03
| SYSRST_RESET
| POSTED_REQUEST
|===

[#section-reset-types]
==== Reset Types
RPMI supports reset types and their values as defined by SBI specification.
Refer to https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sys-reset.adoc#table_srst_system_reset_types[*SRST System Reset Types*^]
in the RISC-V SBI Specification cite:[SBI] for the `RESET_TYPE`.

[#system-reset-notifications]
==== Notifications
This service group does not support any events for notification.

==== Service: SYSRST_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `SYSTEM_RESET`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<system-reset-notifications>>.

[#table_sysreset_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable
1: Enable
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_sysreset_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.
!===
- Other errors <<table_error_codes>>

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state
----
0: Notification is disabled
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===

==== Service: SYSRST_GET_ATTRIBUTES (SERVICE_ID: 0x02)
This service is used to discover the attributes of a reset type. The attribute
flags indicates if a `RESET_TYPE` is supported or not apart from the
System Shutdown and System Cold Reset which are mandatory and supported by
default. System Warm Reset support can be discovered with this service.

[#table_sysreset_getsysresetattrs_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| RESET_TYPE
| uint32
| Reset type. +
Refer <<section-reset-types>> for more details.
|===

[#table_sysreset_getsysresetattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="5,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Attributes returned successfully.

!===
- Other errors <<table_error_codes>>

| 1
| FLAGS
| uint32
| Reset type attributes

[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:1]
! _Reserved_ and must be `0`.

! [0]
! Reset type support

	0b1: Supported.
	0b0: Not supported.
!===
|===

==== Service: SYSRST_RESET (SERVICE_ID: 0x03)
This service is used to initiate the system reset or system shutdown.
The application processor must only request supported reset types, discovered
using the `SYSRST_GET_ATTRIBUTES` service except for System Shutdown and System
Cold Reset which are supported by default. This service does not return response
message in case of successful reset.

[#table_sysreset_sysreset_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| RESET_TYPE
| uint32
| Reset type. +
Refer <<section-reset-types>> for more details.

|===

[#table_sysreset_sysreset_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="5,5a", options="header"]
!===
! Error Code
! Description

! RPMI_ERR_INVALID_PARAM
! Reset type is not supported or invalid.
!===
- Other errors <<table_error_codes>>
|===