
===  Service Group - *SYSTEM_RESET* (servicegroup_id: 0x00002)
This service group offers services for resetting or shutting down the system,
including System Shutdown and System Cold Reset, both of which are
architectural system reset types.

System Shutdown results in all components/devices in the system losing power.
Currently, the AP is the only entity that can request the system shutdown,
which means for Platform Microcontroller it is not important to categorize it
as a graceful or forceful shutdown. In the case of a shutdown request, it is
implicit for the Platform Microcontroller that the AP has prepared itself for
a successful shutdown.

System Cold Reset, also known as Power-On-Reset, involves power cycling the
entire system. Upon a successful system cold reset, all devices undergo power
cycling in an implementation-defined sequence similar to the initial power-on
sequence of the system.

Below table lists the services in this group:
[#table_sysreset_services]
.SYSTEM_RESET Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| SYSRST_ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| SYSRST_GET_ATTRIBUTES		| NORMAL_REQUEST
| 0x03		| SYSRST_RESET			| POSTED_REQUEST
|===

[#system-reset-notifications]
==== Notifications
This service group does not support any event for notifications.

==== Service: *SYSRST_ENABLE_NOTIFICATION*
This service allows the AP to subscribe to SYSTEM_RESET service group
notifications. The platform can optionally support notifications of events
that may occur in the platform. PuC can send these notification messages to
the AP if they are implemented and the AP has subscribed to them. Supported
events are described in <<system-reset-notifications>>.

[#table_sysreset_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_sysreset_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *SYSRST_GET_ATTRIBUTES*
This service is used to discover system reset types supported by the platform. 
*System Shutdown* and *System Cold Reset* are mandatory and are assumed to be
supported. *System Warm Reset* is a qualified reset type which can be discovered
with this service.

[#table_sysreset_getsysresetattrs_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word  | Name         	| Type		| Description
| 0     | RESET_TYPE	| uint32	| Reset type value. +
Refer to https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sys-reset.adoc#table_srst_system_reset_types[*SRST System Reset Types*^]
in the RISC-V SBI Specification cite:[SBI] for the RESET_TYPE definition.
|===

[#table_sysreset_getsysresetattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5a"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Attributes returned successfully.
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| Attributes of the RESET_TYPE
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31]		! Reset type support.

	0b0: RESET_TYPE not supported.
	0b1: RESET_TYPE supported.
! [30:0]	! _Reserved, must be initialized to_ `0`.
!===
|===

==== Service: *SYSRST_RESET*
This service is used to initiate the system shutdown or reset the system
according to the specified type. *System Shutdown* and *System Cold Reset*
are supported implicitly but *System Warm Reset* and other implementation
specific reset types are optional and discoverable.

The AP should only request supported reset types, which are discovered using
the attributes service. Requesting an unsupported or invalid state may result
in the system entering a non-functional state.

[#table_sysreset_sysreset_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word  | Name         	| Type		| Description
| 0     | RESET_TYPE	| uint32	| Reset type value. +
Refer to https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sys-reset.adoc#table_srst_system_reset_types[*SRST System Reset Types*^]
in the RISC-V SBI Specification cite:[SBI] for the RESET_TYPE definition.
|===

[#table_sysreset_sysreset_response_data]
.Response Data
- NA
