:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

=== Service Group: BASE (SERVICEGROUP_ID: 0x0001)
The BASE service group is mandatory and provides the following services:

* Initial handshaking between the application processor and the platform
microcontroller.

* Discovering the RPMI implementation version information.

* Discovering the implementation of a service group.

* Discovering platform specific information.

The following table lists the services in the BASE service group:

[#table_base_services]
.BASE Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| BASE_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| BASE_GET_IMPLEMENTATION_VERSION
| NORMAL_REQUEST

| 0x03
| BASE_GET_IMPLEMENTATION_ID
| NORMAL_REQUEST

| 0x04
| BASE_GET_SPEC_VERSION
| NORMAL_REQUEST

| 0x05
| BASE_GET_PLATFORM_INFO
| NORMAL_REQUEST

| 0x06
| BASE_PROBE_SERVICE_GROUP
| NORMAL_REQUEST

| 0x07
| BASE_GET_ATTRIBUTES
| NORMAL_REQUEST

| 0x08
| BASE_SET_MSI_STATE
| NORMAL_REQUEST

| 0x09
| BASE_GET_MSI_STATE
| NORMAL_REQUEST

| 0x0A
| BASE_SET_MSI_TARGET
| NORMAL_REQUEST

|===

==== RPMI Implementation IDs
The RPMI specification defines space for standard implementation IDs and for
experimental implementation IDs. The experimental implementation IDs can be used
by the implementations until a standard implementation ID is assigned to it.

The RPMI implementations that have been assigned a standard implementation ID
are listed in the table below.

[#table_base_rpmi_impl_id]
.RPMI Implementation IDs
[cols="2, 3a", width=100%, align="center", options="header"]
|===
| Implementation ID
| Name

| 0x00000000
| libRPMI cite:[libRPMI]

| 0x00000001 - 0x7FFFFFFF
| _Reserved for Future Use_

| 0x80000000 - 0xFFFFFFFF
| _Experimental Implementation IDs_
|===

[#base-notifications]
==== Notifications
This service is used by the platform microcontroller to send the asynchronous
message of type notification to the application processor. The message
transfers the events defined by this service group. The events defined are
listed in the below table.

[#table_base_srvgroup_events]
.BASE Service Group Events
[cols="1, 4, 2, 4", width=100%, align="center", options="header"]
|===
| Event ID
| Event Name
| Event Data
| Description

| 0x01
| REQUEST_HANDLE_ERROR
| NA
| This event indicates that the platform microcontroller is unable to
serve the message requests.
|===

==== Service: BASE_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `BASE`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<base-notifications>>.

[#table_base_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable
1: Enable
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_base_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.
!===
- Other errors <<table_error_codes>>

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state
----
0: Notification is disabled
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===

==== Service: BASE_GET_IMPLEMENTATION_VERSION (SERVICE_ID: 0x02)
This service is used to get the RPMI implementation version of the platform
microcontroller. The version returned is a 32-bit composite number containing
the `MAJOR` and `MINOR` version numbers.

[#table_base_getimplversion_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_base_getimplversion_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="2,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! RPMI implementation version returned successfully.
!===
- Other errors <<table_error_codes>>

| 1
| IMPL_VERSION
| uint32
| Implementation version

[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:16]
! `MAJOR` number

! [15:0]
! `MINOR` number
!===
|===

==== Service: BASE_GET_IMPLEMENTATION_ID (SERVICE_ID: 0x03)
This service is used to get a 32-bit RPMI implementation ID assigned to the
software that implements the RPMI specification. Every implementation ID is
unique and listed in the <<table_base_rpmi_impl_id>>.

[#table_base_getimplid_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===


[#table_base_getimplid_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="2,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! RPMI implementation ID returned successfully.
!===
- Other errors <<table_error_codes>>

| 1
| IMPL_ID
| uint32
| Implementation ID
|===

==== Service: BASE_GET_SPEC_VERSION (SERVICE_ID: 0x04)
This service is used to get the implemented RPMI specification version. The
version returned is a 32-bit composite number containing the `MAJOR` and
`MINOR` version numbers.

[#table_base_getspecversion_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_base_getspecversion_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="2,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! RPMI specification version returned successfully.
!===
- Other errors <<table_error_codes>>

| 1
| SPEC_VERSION
| uint32
| RPMI specification version

[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:16]
! `MAJOR` number

! [15:0]
! `MINOR` number
!===
|===

==== Service: BASE_GET_PLATFORM_INFO (SERVICE_ID: 0x05)
This service is used to get additional platform information if available.

[#table_base_getplatinfo_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_base_getplatinfo_response_data]
.Response Data
[cols="1, 3, 4, 6a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="5,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Platform information returned successfully.
!===
- Other errors <<table_error_codes>>

| 1
| PLATFORM_ID_LEN
| uint32
| Platform Identifier field length in bytes.

| 2
| PLATFORM_ID
| uint8[`PLATFORM_ID_LEN`]
| Platform Identifier +
Up to `PLATFORM_ID_LEN` bytes NULL terminated ASCII string.
The use and interpretation of this field is implementation-defined. It can be
used to convey details such as the vendor ID, vendor name, specific product
model, revision, or configuration of the hardware.
|===

==== Service: BASE_PROBE_SERVICE_GROUP (SERVICE_ID: 0x06)
This service is used to probe the implementation of a service group and to
obtain the implemented service group version. The service group version is a
32-bit composite number containing the `MAJOR` and `MINOR` numbers.

If the service group is successfully probed then the implemented service group
version is returned in the `SERVICE_GROUP_VERSION` field. Otherwise it returns
`0`.

[#table_base_probesrvgrp_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| SERVICEGROUP_ID
| uint32
| Service group ID
|===

[#table_base_probesrvgrp_response_data]
.Response Data
[cols="1, 4, 1, 6a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="3,4a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service probed successfully.
!===
- Other errors <<table_error_codes>>

| 1
| SERVICE_GROUP_VERSION
| uint32
| Service group version.
[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:16]
! `MAJOR` number

! [15:0]
! `MINOR` number
!===
|===

==== Service: BASE_GET_ATTRIBUTES (SERVICE_ID: 0x07)
This service is used to discover additional features supported by the BASE
service group.

[#table_base_getbaseattrs_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_base_getbaseattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="2,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Attributes returned successfully.
!===
- Other errors <<table_error_codes>>

| 1
| FLAGS0
| uint32
|
[cols="2,9a", options="header"]
!===
! Bits
! Description

! [31:3]
! _Reserved_ and must be `0`.

! [2]
! RPMI context privilege level.

	0b1: M-mode
	0b0: S-mode

! [1]
! EVENT_NOTIFICATION +

	0b1: Supported
	0b0: Not supported

! [0]
! MSI support in platform +

	0b1: Supported
	0b0: Not supported
!===

| 2
| FLAGS1
| uint32
| _Reserved_ and must be `0`.

| 3
| FLAGS2
| uint32
| _Reserved_ and must be `0`.

| 4
| FLAGS3
| uint32
| _Reserved_ and must be `0`.
|===

[#srvgrp_base_set_msi_state]
==== Service: BASE_SET_MSI_STATE (SERVICE_ID: 0x08)
This service is used to control the MSI state such as enable/disable the MSI
which the platform microcontroller can use as a doorbell to the application
processor. The application processor can discover the availability of the MSI
support via the `BASE_GET_ATTRIBUTES` service.

If the MSI support is available, the application processor can enable the
MSI using this service. If the MSI is not supported, the appropriate error code
is returned. The platform microcontroller can only send the MSI if it is enabled
and the MSI target address configured is valid. The target configuration is done
by another defined service `BASE_SET_MSI_TARGET`.

[#table_base_setmsistate_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATE
| uint32
| MSI state
[cols="2,9a", options="header"]
!===
! Bits
! Description

! [31:1]
! _Reserved_ and must be `0`.

! [0]
! MSI enable control.

	0b1: Enable MSI.
	0b0: Disable MSI.

!===
|===

[#table_base_setmsistate_response_data]
.Response Data
[cols="1, 1, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="7,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! MSI is enabled or disabled successfully.

! RPMI_ERR_NOT_SUPPORTED
! MSI is not supported.

! RPMI_ERR_INVALID_PARAM
! `STATE` value is reserved or invalid.

!===
- Other errors <<table_error_codes>>
|===

[#srvgrp_base_get_msi_state]
==== Service: BASE_GET_MSI_STATE (SERVICE_ID: 0x09)
This service is used to get the state of the MSI, whether the MSI is
enabled/disabled or if the MSI is currently pending and the platform microcontroller
is unable to send.

NOTE: The MSI can be pending for a number of reasons, for example, if the MSI
target address and data are not configured, or if the configured MSI target address
is not valid. The application processor should configure a valid MSI target using
the `BASE_SET_MSI_TARGET` service.

If the MSI is not supported by the platform microcontroller, the appropriate
error code will be returned.

NOTE: Not all bits defined in the `STATE` field have a corresponding bit in the 
`BASE_SET_MSI_STATE` service. There may be additional state bits which are defined
which are read-only and cannot be controlled by the application processor.

[#table_base_getmsistate_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_base_getmsistate_response_data]
.Response Data
[cols="1, 1, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="7,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! MSI state is returned successfully.

! RPMI_ERR_NOT_SUPPORTED
! MSI is not supported.
!===
- Other errors <<table_error_codes>>

| 1
| STATE
| uint32
| MSI state
[cols="2,9a", options="header"]
!===
! Bits
! Description

! [31:2]
! _Reserved_ and must be `0`.

! [1]
! MSI pending state. +

	0b1: MSI is pending.
	0b0: MSI is not pending.

! [0]
! MSI enable state.

	0b1: MSI enabled
	0b0: MSI disabled

!===
|===


[#srvgrp_base_set_msi_target]
==== Service: BASE_SET_MSI_TARGET (SERVICE_ID: 0x0A)
This service is used to configure the MSI target address and data which the
platform microcontroller can use as a doorbell to the application processor. The
application processor may first discover the MSI support via the
`BASE_GET_ATTRIBUTES` service. 

The platform microcontroller can only send the MSI if it is enabled and the
configured MSI target address is valid. The platform must validate the MSI target
address before sending the MSI.

If MSI is not supported or not enabled, this service will be ignored and an
appropriate error will be returned. If the MSI target address is invalid then
an appropriate error code will be returned.

NOTE: The platform microcontroller can use MSI for sending the MSI
directly or injecting wired interrupt in the application processor. If the MSI
target address is IMSIC, then the application processor will take MSI whereas
if the MSI target address is `setipnum` of the APLIC then the application
processor will take the wired interrupt.

[#table_base_setmsitarget_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| MSI_ADDRESS_LOW
| uint32
| Lower 32-bit of the MSI address.

| 1
| MSI_ADDRESS_HIGH
| uint32
| Upper 32-bit of the MSI address.

| 2
| MSI_DATA
| uint32
| 32-bit MSI data
|===

[#table_base_setmsitarget_response_data]
.Response Data
[cols="1, 1, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="7,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! MSI address and data are configured successfully.

! RPMI_ERR_NOT_SUPPORTED
! MSI is not supported.

! RPMI_ERR_INVALID_ADDR
! MSI target address is invalid or it is not `4-byte` aligned.
!===
- Other errors <<table_error_codes>>
|===
