:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - VOLTAGE (SERVICEGROUP_ID: 0x0006)
The system can be classified into multiple domains for voltage control. Each
domain is the logical grouping of one or more devices powered by a single
voltage source. Actions associated with messages within each domain control the
voltage source, thereby influencing either the individual device or the collective
group of devices sharing the same voltage source. Each domain is identified by
`DOMAIN_ID` which is a 32-bit integer starting from `0`.

The following table lists the services in the VOLTAGE service group:
[#table_voltage_services]
.VOLTAGE Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| VOLT_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| VOLT_GET_NUM_DOMAINS
| NORMAL_REQUEST

| 0x03
| VOLT_GET_ATTRIBUTES
| NORMAL_REQUEST

| 0x04
| VOLT_GET_SUPPORTED_LEVELS
| NORMAL_REQUEST

| 0x05
| VOLT_SET_CONFIG
| NORMAL_REQUEST

| 0x06
| VOLT_GET_CONFIG
| NORMAL_REQUEST

| 0x07
| VOLT_SET_LEVEL
| NORMAL_REQUEST

| 0x08
| VOLT_GET_LEVEL
| NORMAL_REQUEST

|===

[#voltage-level-format-section]
==== Voltage Level Format
There are 2 types of voltage level formats supported in the VOLTAGE service
group. The voltage levels are represented as a group.

===== Discrete Format
A set of discrete voltage levels arranged in a sequence, starting from the
lowest value at the lowest index and increasing sequentially to higher levels.
The following table shows the structure of the discrete format.

```c
[voltage1, voltage2, voltage3, ... , voltageN]

where:
voltage1 < voltage2 < voltage3 < ... < voltageN
```

[cols="1,2,5" width=100%, align="center", options="header"]
|===
| Word
| Name
| Description

| 0
| VOLTAGE
| Discrete voltage level in microvolts (uV).
|===

===== Simple-Linear Format
A linear range of voltage levels with a constant step size. The following table
shows the structure of the simple-linear voltage format.

```c
[voltage_minimum, voltage_maximum, voltage_step]
```

[cols="1,2,5" width=100%, align="center", options="header"]
|===
| Word
| Name
| Description

| 0
| VOLTAGE_MIN
| Lower boundary of voltage level in microvolts (uV).

| 1
| VOLTAGE_MAX
| Upper boundary of voltage level in microvolts (uV).

| 2
| STEP
| Step size in microvolts (uV).
|===

[#voltage-notifications]
==== Notifications
This service group does not support any events for notification.

==== Service: VOLT_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `VOLTAGE`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<voltage-notifications>>.

[#table_voltage_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state. +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable.
1: Enable.
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_voltage_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.
!===
- Other errors <<table_error_codes>>.

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state.
----
0: Notification is disabled.
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===


==== Service: VOLT_GET_NUM_DOMAINS (SERVICE_ID: 0x02)
This service is used to query the number of voltage domains available in the
system.

[#table_voltage_getnumdomains_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_voltage_getnumdomains_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="2,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.
!===
- Other errors <<table_error_codes>>.

| 1
| NUM_DOMAINS
| uint32
| Number of voltage domains.
|===

==== Service: VOLT_GET_ATTRIBUTES (SERVICE_ID: 0x03)
Each domain may support multiple voltage levels, which are permitted by the domain
for operation. The number of levels indicates the total count of voltage levels
supported within a voltage domain. Transition latency denotes the maximum time
required for the voltage to stabilize upon a change in the regulator. Depending
on the hardware, voltage levels can be of various formats, and the current
service supports discrete and simple-linear formats. Each domain can
support only one voltage level format. Additional voltage formats can be
accommodated in the future if required.

[#table_voltage_getdomainattrs_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.
|===

[#table_voltage_getdomainattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.
[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `DOMAIN_ID` is invalid.
!===
- Other errors <<table_error_codes>>.

| 1
| FLAGS
| uint32
| [cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:4]
! _Reserved_ and must be `0`.

! [3:1]
! Voltage format. +
Refer to <<voltage-level-format-section>> for more details.
----
0b000: Discrete voltage.
0b001: Simple-linear.
0b010 - 0b111: Reserved.
----

! [0]
! Voltage domain control support.

----
0b0: Voltage domain can be enabled/disabled.
0b1: Voltage domain is always-on, voltage value can be changed in the
supported voltage range.
----
!===
| 2
| NUM_LEVELS
| uint32
| Number of voltage levels (number of arrays) supported by the domain. Each
simple-linear format voltage level represents 1 voltage level.

| 3
| TRANS_LATENCY
| uint32
| Transition latency, in microsecond (us).

| 4:7
| DOMAIN_NAME
| uint8[16]
| Voltage domain name, a NULL-terminated ASCII string up to 16-bytes.
|===

==== Service: VOLT_GET_SUPPORTED_LEVELS (SERVICE_ID: 0x04)
Each domain may support multiple voltage levels which are allowed by the domain
to operate. The number of voltage levels returned depends on the format of the
voltage level.

The total number of words required to represent the voltage levels in one message
cannot exceed the total words available in one message `DATA` field. If the number
of levels exceeds this limit, the platform microcontroller will return the maximum
number of levels that can be accommodated in one message and adjust the `REMAINING`
field accordingly. When the `REMAINING` field is not zero, the application processor
must make subsequent service calls with the appropriate `VOLTAGE_LEVEL_INDEX` set
to retrieve the remaining voltage levels. It is possible that multiple service
calls may be necessary to retrieve all the voltage levels.

[#table_voltage_getdomainlevels_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.

| 1
| VOLTAGE_LEVEL_INDEX
| uint32
| Voltage level index.
|===

[#table_voltage_getdomainlevels_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.
[cols="7,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully and voltage levels returned.

! RPMI_ERR_INVALID_PARAM
! Voltage `DOMAIN_ID` is invalid.

! RPMI_ERR_INVALID_PARAM
! `VOLTAGE_LEVEL_INDEX` is invalid.

!===
- Other errors <<table_error_codes>>.
| 1
| FLAGS
| uint32
| _Reserved_ and must be `0`.

| 2
| REMAINING
| uint32
| Remaining number of voltage levels (number of arrays).

| 3
| RETURNED
| uint32
| Number of voltage levels (number of arrays) returned in this request.

| 4
| VOLTAGE_LEVEL[N]
| uint32[]
| Voltage levels. +
Refer to <<voltage-level-format-section>> for more details.

|===

==== Service: VOLT_SET_CONFIG (SERVICE_ID: 0x05)
This service is used to configure a voltage domain.

[#table_voltage_setdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.

| 1
| CONFIG
| uint32
| Voltage domain config.

[cols="2,5a", options="header"]
!===
! Bits
! *Description*

! [31:1]
! _Reserved_ and must be `0`.

! [0]
!
Voltage supply control.
----
0b1: Enable voltage supply.
0b0: Disable voltage supply.
----
!===

|===

[#table_voltage_setdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! Voltage `DOMAIN_ID` or `CONFIG` is invalid.

!===
- Other errors <<table_error_codes>>.
|===

==== Service: VOLT_GET_CONFIG (SERVICE_ID: 0x06)
This service is used to get the configuration of a voltage domain.
[#table_voltage_getdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.

|===

[#table_voltage_getdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! Voltage `DOMAIN_ID` not found.

!===
- Other errors <<table_error_codes>>.
| 1
| CONFIG
| uint32
| Voltage domain config.
[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:1]
! _Reserved_ and must be `0`.
! [0]
! Voltage supply state.
----
0b1: Voltage supply is enabled.
0b0: Voltage supply is disabled.
----
!===

|===


==== Service: VOLT_SET_LEVEL (SERVICE_ID: 0x07)
This service is used to set the voltage level in microvolts of a voltage domain.

[#table_voltage_setdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.

| 1
| VOLTAGE_LEVEL
| int32
| Voltage level, in microvolts.

|===

[#table_voltage_setdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! Voltage `DOMAIN_ID` or `VOLTAGE_LEVEL` is invalid.

!===

- Other errors <<table_error_codes>>.
|===


==== Service: VOLT_GET_LEVEL (SERVICE_ID: 0x08)
This service is used to get the current voltage level in microvolts of a
voltage domain.

[#table_voltage_getdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Voltage domain ID.

|===

[#table_voltage_getdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! Voltage `DOMAIN_ID` not found.

!===
- Other errors <<table_error_codes>>.

| 1
| VOLTAGE_LEVEL
| int32
| Voltage level, in microvolts.
|===
