:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - *SYSTEM_SUSPEND* (servicegroup_id: 0x00003)
This service group provides services to put the entire system in a low power 
suspend state. All harts except the hart doing system suspend need to be in
the STOPPED state.

Below if the list of services in this group:
[#table_syssuspend_services]
.SYSTEM_SUSPEND Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| SYSSUSP_ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| SYSSUSP_GET_ATTRIBUTES	| NORMAL_REQUEST
| 0x03		| SYSSUSP_SUSPEND		| NORMAL_REQUEST
|===

[#system-suspend-notifications]
==== Notifications
This service group does not support any event for notification.

==== Service: *SYSSUSP_ENABLE_NOTIFICATION*
This service allows the AP to subscribe to SYSTEM_SUSPEND service group
notification. The platform can optionally support notifications of events
that may occur in the platform. PuC can send these notification messages to
the AP if they are implemented and the AP has subscribed to them. Supported
events are described in <<system-suspend-notifications>>.

[#table_syssuspend_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_syssuspend_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *SYSSUSP_GET_ATTRIBUTES*
This service is used to discover the SYSTEM_SUSPEND attributes with a specific
SUSPEND_TYPE.

[#table_syssuspend_getsyssuspendattrs_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word  | Name         	| Type		| Description
| 0     | SUSPEND_TYPE	| uint32	| Suspend type value. +
Refer to https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sys-suspend.adoc#table_susp_sleep_types[*SUSP System Sleep Types*^]
in the RISC-V SBI Specification cite:[SBI] for the SUSPEND_TYPE definition.
|===

[#table_syssuspend_getsysuspendattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5a"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Attributes returned successfully.
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| Attributes of the SUSPEND_TYPE
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31]		!

	0b0: Custom resume address not supported.
	0b1: Custom resume address supported.
! [30]		!

	0b0: Suspend not supported
	0b1: Suspend supported
! [29:0]	! _Reserved, must be initialized to_ `0`.
!===
|===

==== Service: *SYSSUSP_SUSPEND*
This service puts the system into low power state based on the specified suspend
type. It requires that all harts except the calling hart to be in the STOPPED
state as defined by the Hart State Management service group. The system
transitions into the low power state only after the requesting hart executes
the WFI instruction.

[#table_syssuspend_syssuspend_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word  | Name         	| Type		| Description
| 0	| HART_ID	| uint32	| Hart ID of the calling hart.
| 1     | SUSPEND_TYPE	| uint32	| Suspend type value. +
Refer to https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sys-suspend.adoc#table_susp_sleep_types[*SUSP System Sleep Types*^]
in the RISC-V SBI Specification cite:[SBI] for the SUSPEND_TYPE definition.
| 2	| RESUME_ADDR_LOW	| uint32	| Lower `32 bits` address
| 3	| RESUME_ADDR_HIGH	| uint32	| Upper `32 bits` address
|===

[#table_syssuspend_syssuspend_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_ERROR_NOT_SUPPORTED ! SUSPEND_TYPE is not supported. The AP must use the
SYSSUSP_GET_ATTRIBUTES service to determine if SUSPEND_TYPE is supported
or not. Only supported SUSPEND_TYPE must be used with this service.
!===
- Other errors <<table_error_codes>>
|===
