:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - SECURE_EXECUTION (SERVICEGROUP_ID: 0x000A)
This SECURE_EXECUTION service group is designed to be used for software invocation
of Management Mode (MM) in a secure execution environment or OS in a Trusted
Execution Environment (TEE). For general background on Management Mode, refer to the
Platform Initialization (PI) specifications cite:[PI], Volume 4: Management Mode
Core Interface. Management Mode provides an environment for implementing OS agnostic
services (MM services) like secure variable storage, and firmware updates in system
firmware. This service group describes the interfaces for invoking MM or TEE OS
services synchronously, the `SE_COMMUNICATE` serves as the world-switch synchronous
call from the non-secure to the secure world while the `SEE_COMPLETE` facilitates
synchronous return from the secure to the non-secure world.

The following table lists the services in the SECURE_EXECUTION service group:

[#table_se_services]
.SECURE_EXECUTION Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| SE_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| SE_GET_SHARED_MEMORY
| NORMAL_REQUEST

| 0x03
| SE_COMMUNICATE
| NORMAL_REQUEST
|===

[#secure-execution-notifications]
==== Notifications
This service group does not support any event for notification.

==== Service: SE_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to SECURE_EXECUTION
service group notifications. Platform can optionally support notifications of
events which might occur in the platform. Platform microcontroller can send
these notification messages to application processor if they are implemented
and application processor has subscribed to these. Events supported are described
in <<secure-execution-notifications>>.

[#table_se_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| Event to be subscribed for notification.
|===

[#table_se_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.

!===
- Other errors <<table_error_codes>>
|===

==== Service: SE_GET_SHARED_MEMORY (SERVICE_ID: 0x02)
This service returns the shared memory to be used between secure execution environment and non-secure world.

[#table_se_get_shared_memory_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_se_get_shared_memory_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code
[cols="4,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_DENIED
! Denied due to no permission.

!===
- Other errors <<table_error_codes>>

| 1
| SE_COMM_SHARED_MEM_ADDR_LOW
| uint32
| Lower 32-bit of the SE data's physical address between non-secure and secure world.

| 2
| SE_COMM_SHARED_MEM_ADDR_HIGH
| uint32
| Upper 32-bit of the SE data's physical address between non-secure and secure world.
|===



==== Service: SE_COMMUNICATE (SERVICE_ID: 0x03)
This service invokes an MM or TEE OS service implemented in the secure or trusted
execution environment. The `SE_COMM_DATA_OFFSET` and `SE_COMM_DATA_SIZE` contains
offset and the size of the data stored in the secure and non-secure world's shared
memory to identify and invoke the SE service. The readiness of this synchronous
request from the non-secure world is signaled by the `SEE_COMPLETE` call from the
secure world.

[#table_se_communicate_request_data]
.Request Data
[cols="1, 5, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| SE_COMM_DATA_OFFSET
| uint32
| 32-bit offset of the MM or TEE data stored in the shared memory from non-secure to secure world.

| 1
| SE_COMM_DATA_SIZE
| uint32
| 32-bit of the MM or TEE data's length from non-secure to secure world.
|===

[#table_se_communicate_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code

[cols="4,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_DENIED
! Denied due to no permission.

!===
- Other errors <<table_error_codes>>
|===
