
===  Service Group - *DEVICE_POWER* (servicegroup_id: 0x00008)
This DEVICE_POWER service group provides messages to manage the power states of
a device power domain. This service group is used only for device power
management since System and CPU power management is handled by already defined 
service groups such as SYSTEM_RESET, SYSTEM_SUSPEND and HART_STATE_MANAGEMENT.

A domain can consist of one device if its power states can be controlled 
independently or it may also have multiple devices if they all share the same 
power control lines and power states can only be changed collectively.
Each domain must support ON and OFF states along with custom power states which 
are discoverable.  Domains may also have power states which may preserve the 
context. The level of context preserved will depends on the level of power state.

Power states for domains will be discovered via supported hardware description
mechanisms where the values for ON and OFF are already fixed and known. 
The power state encodes both the power state value and the context preserved or 
lost information corresponding to that state.

The DEVICE_POWER services take a 32-bit integer identifier known as `DOMAIN_ID`
to specify the device power domain. These `DOMAIN_ID` identifiers are sequential
and start from 0.

[#table_devpower_powerstate_data]
.Power States Encoding
[cols="2, 2, 5a", width=100%, align="center", options="header"]
|===
| POWER_STATE (uint32)	| Field 	| Description
| POWER_STATE[31]	| CONTEXT	|

	0b0: Context is preserved
	0b1: Context is lost
| POWER_STATE[30:16]	| RESERVED	| _Reserved_
| POWER_STATE[15:0]	| VALUE		|
[cols="2,5"]
!===
! *Value* 	!  *Description*
! 0x0000	! ON with POWER_STATE[31] = 1
! 0x0001	! _Reserved_
! 0x0002	! _Reserved_
! 0x0003	! OFF with POWER_STATE[31] = 0
! 0x0004 - 0x0FFF ! _Reserved_
! 0x1000 - 0xFFFF ! Vendor specific states
!===
|===

[#table_devpower_services]
.DEVICE_POWER Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| DPWR_ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| DPWR_GET_NUM_DOMAINS		| NORMAL_REQUEST
| 0x03		| DPWR_GET_ATTRIBUTES		| NORMAL_REQUEST
| 0x04		| DPWR_SET_STATE		| NORMAL_REQUEST
| 0x05		| DPWR_GET_STATE		| NORMAL_REQUEST
|===

[#device-power-notifications]
==== Notifications
This service group does not support any event for notification.

==== Service: *DPWR_ENABLE_NOTIFICATION*
This service allows the AP to subscribe to DEVICE_POWER service group notifications.
The platform can optionally support notifications of events that may occur in the platform.
The PuC can send these notification messages to the AP if they are implemented
and the AP has subscribed to them. The supported events are described in
<<device-power-notifications>>.
 
[#table_devpower_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_devpower_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notification is subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notification is not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *DPWR_GET_NUM_DOMAINS*
This service is used to query the number of device power domains available which
can be controlled by the client. The number of domains returned can be less than
the actual number of domains present with the platform.

[#table_devpower_getdomains_request_data]
.Request Data
- NA

[#table_devpower_getdomains_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
!===
- Other errors <<table_error_codes>>
| 1	| NUM_DOMAINS	| uint32 	| Number of device power domains
|===


==== Service: *DPWR_GET_ATTRIBUTES*
This service is used to query the attributes of a device power domain.

[#table_devpower_getattrs_request_data]
.Request Data
[cols="1, 4, 1, 6", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Device power domain ID
|===

[#table_devpower_getattrs_response_data]
.Response Data
[cols="1, 4, 1, 6a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Device power domain not found
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS			| uint32	| _Reserved_
| 2	| TRANSITION_LATENCY	| uint32 	| Worst case transition latency 
of domain from one power state to another, in microseconds (us)
| 3:6	| DEVICE_POWER_DOMAIN_NAME | uint8[16]	| Device power domain
name, a NULL-terminated ASCII string up to 16-bytes.
|===


==== Service: *DPWR_SET_STATE*
This service is used to change the power state of a device power domain.

[#table_devpower_setstate_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Device power domain ID
| 1	| POWER_STATE	| uint32	| This field indicates the power state to which the power domain should transition. The specific power states and their 
meanings may vary depending on the implementation, but generally, they include 
values such as "ON", "OFF" and vendor specific power state. +
See Power States description in the <<table_devpower_powerstate_data>>.
|===

[#table_devpower_setstate_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Device power domain not found.
! RPMI_ERROR_INVALID_PARAMETER ! Invalid or not supported POWER_STATE value.
! RPMI_ERROR_DENIED ! Client does not have permissions to change the device power domain power state.
! RPMI_ERROR_HW_FAULT ! Failed due to hardware error.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *DPWR_GET_STATE*
This service is used to get the current power state of a device power domain.

[#table_devpower_getstate_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Device power domain ID
|===

[#table_devpower_getstate_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="4,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Device power domain not found.
! RPMI_ERROR_DENIED ! Client does not have permissions to change the device power domain power state.
!===
- Other errors <<table_error_codes>>
| 1	| POWER_STATE	| uint32	| This field indicates the current power state
of the specified domain. The power state can be one of several predefined values,
such as ON, OFF, or vendor specific implementation.
See Power States description in the <<table_devpower_powerstate_data>>.
|===
