
===  Service Group - *SECURE_MANAGEMENT_MODE* (servicegroup_id: 0x0000A)
This secure management mode service group is used for software invocation of 
Management Mode (MM) in a secure execution environment. PI Management Mode (MM) 
provides an environment for implementing OS agnostic services (MM services) like
secure variable storage, and firmware updates in system firmware. The services 
can be invoked synchronously and asynchronously. This service group describes 
the interfaces for invoking MM services synchronously. For more information on 
Management Mode (MM), check the https://uefi.org/sites/default/files/resources/UEFI_PI_Spec_1_8_March3.pdf[Platform Initialization (PI) specifications, 
Volume 4: Management Mode Core Interface].

[#table_smm_services]
.Secure Management Mode Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 				| Request Type
| 0x01		| ENABLE_NOTIFICATION			| NORMAL_REQUEST
| 0x02		| SMM_VERSION				| NORMAL_REQUEST
| 0x03		| SMM_COMMUNICATE			| NORMAL_REQUEST
| 0x04		| SMM_COMPLETE				| NORMAL_REQUEST
| 0x05		| SMM_INITIALIZE			| NORMAL_REQUEST
|===

==== Secure Management Mode Notifications
This service group does not support any event for notification.

==== Service: *ENABLE_NOTIFICATION*
This service allows AP to subscribe to secure management mode service group 
notifications.
Platform can optionally support notifications of events which might occur in the
platform. Management Mode firmware can send these notification messages to AP if
they are implemented and AP has subscribed to these. Events supported are 
described above in Secure Management Mode Notifications. 

[#table_smm_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_smm_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===


==== Service: *SMM_VERSION*
This service returns the version of a secure management mode service.

[#table_smm_version_request_data]
.Request Data
- NA

[#table_smm_version_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_DENIED ! Denied due to no permission.
!===
- Other errors <<table_error_codes>>
| 1	| MM_VERSION 	| uint32 	| Management mode service version.
[cols="2,5"]
!===
! *Bits* 		!  *Description*
! [31:16]		! Major Version
! [15:0]	 	! Minor Version
!===
|===


==== Service: *SMM_COMMUNICATE*
This service is used to invoke a Management Mode service that is implemented in 
the secure execution environment. The `MM_COMM_BUFFER` field contains data to 
identify and invoke the Management Mode service. This synchronous call is 
returned by using `SMM_COMPLETE` service.

[#table_smm_communicate_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		 | Type		| Description
| 0	| MM_COMM_BUFFER | uint32	| MM data from non-secure to secure 
world.
|===

[#table_smm_communicate_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="4,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_DENIED ! Denied due to no permission.
!===
- Other errors <<table_error_codes>>
|===



==== Service: *SMM_COMPLETE*
This service is used as the “**world-switch synchronous call**” at the end
of a synchronous `SMM_COMMUNICATE` service to signal the readiness for handling 
the synchronous request. The `MM_COMM_BUFFER` field contains the returned data 
of the MM service invoked in secure execution environment.

[#table_smm_complete_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		 | Type		| Description
| 0	| MM_COMM_BUFFER | uint32	| MM data from non-secure to secure 
world.
|===

[#table_smm_complete_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="4,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_DENIED ! Denied due to no permission.
!===
- Other errors <<table_error_codes>>
|===



==== Service: *SMM_INITIALIZE*
This is an optional service. The MM modules may come in the firmware volume or 
FD files, loaded by the M-mode firmware like u-boot spl and initialized by the 
OpenSBI domain during the M-Mode firmware boot time. If so, this service api is 
not needed as default. But there is still case that the MM modules are requested
to be loaded or initialized by the S-Mode firmware components, thus this service
is used to launch the MM related modules as needed.

[#table_smm_initialize_request_data]
.Request Data
[cols="1, 4, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| HART_ID	| uint8		| Hart ID to launch
| 1	| DOMAIN_ID	| uint8		| Secure domain ID to be used to 
initialize the mm modules.
| 2:3	| FLAGS		| uint16	|
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:1]	! _Reserved_
! [0]		! 

	0b0: No payload information.
	0b1: With payload information.
!===
| 4:5	| MM_PAYLOAD_BASE	| uint64	| Base address of MM payload
loaded by the S-Mode firmware.
| 6:7	| MM_PAYLOAD_SIZE	| uint64	| MM payload size loaded by the
S-Mode firmware.
| 8:263 | MM_PAYLOAD_SIGNATURE	| uint8		| MM payload signature loaded by
the S-Mode firmware.
|===

[#table_smm_initialize_response_data]
.Response Data
[cols="1, 4, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_DENIED ! Denied due to no permission.
!===
- Other errors <<table_error_codes>>
|===