
===  Service Group - *VOLTAGE* (servicegroup_id: 0x00006)
The complete system can be classified into multiple domains for voltage control. Each domain is the logical group of one or more devices that have a single 
voltage source. The action corresponding to the messages in this group controls 
the voltage source which affects the device or the group of devices together 
since those devices share the same voltage source. Each domain is identified by domain_id which is a `32 bit`` integer starting from `0`.

Below table lists the services in this group:
[#table_voltage_services]
.Voltage Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 		| Request Type
| 0x01		| ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| GET_NUM_DOMAINS	| NORMAL_REQUEST
| 0x03		| GET_DOMAIN_ATTRIBUTES	| NORMAL_REQUEST
| 0x04		| GET_DOMAIN_LEVELS	| NORMAL_REQUEST
| 0x05		| SET_DOMAIN_CONFIG	| NORMAL_REQUEST
| 0x06		| GET_DOMAIN_CONFIG	| NORMAL_REQUEST
| 0x07		| SET_DOMAIN_LEVEL	| NORMAL_REQUEST
| 0x08		| GET_DOMAIN_LEVEL	| NORMAL_REQUEST
|===

==== Voltage Notifications
This service group does not support any event for notification.

==== Service: *ENABLE_NOTIFICATION*
This service allows AP to subscribe to voltage service group notifications.
Platform can optionally support notifications of events which might occur in the platform. PuC can send these notification messages to AP if they are implemented
and AP has subscribed to these. Events supported are described above in Voltage Notifications. 
 

[#table_voltage_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 5", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_voltage_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *GET_NUM_DOMAINS*
Request for number of domains available in the system.

[#table_voltage_getnumdomains_request_data]
.Request Data
- NA

[#table_voltage_getnumdomains_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and voltage domains returned
as NUM_DOMAINS.
!===
- Other errors <<table_error_codes>>
| 1	|	NUM_DOMAINS 	| uint32 	| Number of Domains
|===

==== Service: *GET_DOMAIN_ATTRIBUTES*
Each domain may have supported multiple voltage levels which are allowed by the 
domain to operate. This message for each domain returns a domain name which is a
null terminated ASCII string of `16 byte`. 
Number of levels represents the total number of voltage levels supported by a 
voltage domain.  Transition latency is the max time taken for voltage to 
stabilize when changed on the regulator. Voltage levels depending on the 
hardware can be of different formats and this service currently supports Simple 
Linear, Multi-Linear and Discrete range. More voltage formats can be supported 
in future if required.
[#table_voltage_getdomainattrs_request_data]
.Request Data
[cols="1, 2, 1, 5", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainattrs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| 
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:30]	! VOLTAGE_FORMAT

	0b00: Fixed Voltage

	0b01: Simple Linear Range containing single triplet 
	(min_uV, max_uV, step_uV).
	
	0b10: Multi-Linear range containing multiple linear ranges of type `0x1` 
	where each range contains (min_uV, min_sel, max_sel, step_uV).
	
	0b11: Discrete range.
! [29:1]	! _Reserved_
! [0]		! ALWAYS_ON

	0b0: Voltage domain can be enabled/disabled.

	0b1: Voltage domain is always-on, voltage value can be changed in the 
	supported voltage range.
!===
| 2	|NUM_LEVELS	 | uint32	| Number of voltage levels supported by 
domain. Some values are dependent on the VOLTAGE_FORMAT.
[cols="2,5a"]
!===
! *Value* 	!  *Description*
! 1		! VOLTAGE_FORMAT=`0x0`
! 3		! VOLTAGE_FORMAT=`0x1`
! N		! VOLTAGE_FORMAT=`0x2` or `0x3`. Based on the format here 
each item can be a single voltage value or tuple of values. Check VOLTAGE_FORMAT
field in FLAGS.
!===
| 3	| TRANSITION_LATENCY	| uint32	| Transition Latency
| 4:7	| VOLTAGE_DOMAIN_NAME	| uint8[16]	| Voltage domain name
|===

==== Service: *GET_DOMAIN_LEVELS*
Each domain may support multiple voltage levels which are allowed by the domain 
to operate.
Depending on the Power supply/Voltage Regulator the domain may support voltage 
levels which can be either discrete or stepwise range. Discrete voltage range 
will be in sequence starting from lower voltage value at the lowest index to 
higher voltage level with increasing index. Number of voltage levels returned 
depends on the format of the voltage level. Total words required for the number 
levels according to the format in one message cannot exceed the total words 
available in one message DATA field. If they exceed then PuC will return the 
number of levels which can be accommodated in one message and set the REMAINING 
field accordingly. AP, when REMAINING field is not 0 must call this service 
again with appropriate VOLTAGE_LEVEL_INDEX set to get the remaining voltage 
levels. It's possible that multiple service calls may be required to get all the
voltage levels.

[#table_voltage_getdomainlevels_request_data]
.Request Data
[cols="1, 2, 1, 5", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| VOLTAGE_LEVEL_INDEX | uint32	| Voltage level index
|===

[#table_voltage_getdomainlevels_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and voltage levels returned.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! VOLTAGE_LEVEL_INDEX is not valid
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| _Reserved_ and must be `0`.
| 2	| REMAINING	| uint32	| Remaining number of levels.
| 3	| RETURNED	| uint32	| Number of levels returned so far.
| 4	| VOLTAGE[0]	| uint32	| Voltage array where each entry in the
array is a voltage level in microvolts(uV).

N is specified by the GET_DOMAIN_ATTRIBUTES.NUM_LEVELS. Voltage represented in 
microvolt (uV).

If the bits in GET_DOMAIN_ATTRIBUTES.FLAGS[31:30] are set to `0`, VOLTAGE[0] 
contains a fixed voltage level in the array. +
`VOLTAGE[0]: volt_uV`

If the bits in GET_DOMAIN_ATTRIBUTES.FLAGS[31:30] are set to `1`, it means that 
the voltage array contains three entries as below: +
`VOLTAGE[0]: min_uV +
VOLTAGE[1]: max_uV +
VOLTAGE[2]: step_uV`
 
If the bits in GET_DOMAIN_ATTRIBUTES.FLAGS[31:30] are set to `2`, it indicates 
that the voltage array contains multiple groups of four entries. Each group 
represent a linear voltage range and consists of the following entries: +
`VOLTAGE[0] = min_uV +
VOLTAGE[1] = min_sel +
VOLTAGE[2] = max_sel +
VOLTAGE[3] = step_uV`

If the bits in  GET_DOMAIN_ATTRIBUTES.FLAGS[31:30] are set to 3, it means that 
the entry array contains discrete voltage levels listed in ascending numeric 
order(_Low index represents minimum voltage level, and high index represents
maximum voltage level supported_). +
`VOLTAGE[0]: Voltage0 +
VOLTAGE[1]: Voltage1 +
VOLTAGE[2]: Voltage2 +
VOLTAGE[N - 1]: Voltage(N – 1)`
| 5	| VOLTAGE[1]	| int32	|
| ...	| VOLTAGE[N-1]	| int32	|
|===

==== Service: *SET_DOMAIN_CONFIG*
Set voltage config message enable or disable any domain. Enabling the voltage 
means applying the domain with the voltage level to operate normally. AP can 
enable the voltage to any domain without knowing the actual voltage levels. 
Disabling the voltage level means disabling the voltage supply to the domain.

CONFIG field encodes these discrete settings which do not require AP to know 
the voltage level
[#table_voltage_setdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| CONFIG	| uint32	| Voltage domain config
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:1]	! _Reserved_
! [0]		! 

	0b0: Disable voltage for domain

	0b1: Enable voltage for domain
!===
|===

[#table_voltage_setdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! Voltage config is not supported by the
spefified voltage domain.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *GET_DOMAIN_CONFIG*
Get voltage config message request for the configuration of the voltage domain 
currently set.
[#table_voltage_getdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| CONFIG	| uint32	| Voltage domain config
[cols="2,5a"]
!===
! *Value* 	!  *Description*
! 0x0		! Disabled 
! 0x1		! Enabled
!===
|===


==== Service: *SET_DOMAIN_LEVEL*
Set the voltage level in microvolts(uV) of a voltage domain 

[#table_voltage_setdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| VOLTAGE_LEVEL	| int32		| Voltage level
|===

[#table_voltage_setdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! Voltage level is not supported by specified
voltage domain.
!===
- Other errors <<table_error_codes>>
|===


==== Service: *GET_DOMAIN_LEVEL*
Get the current voltage level in microvolts(uV) of a voltage domain.

[#table_voltage_getdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 5a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| VOLTAGE_LEVEL	| int32	| Voltage Level
|===