=== Service Group - *CPPC* (servicegroup_id: 0x00005)
This service group defines the services to control CPU performance by managing a set of registers and a dedicated physical memory block, which will define Fast-channel access to each hart in the system. Hart writes a specific 32 bits desired performance number in Fast-channel memory. PuC decodes the request and performs the corresponding CPPC operations.

CPPC physical memory will have enough space to accommodate all available harts. Hart can send an RPMI message GET_CPPC_PERF_CHAN_ADDR to query the physical address of that particular hart.

Once Hart receives the physical address of the REQ-ACK registers, Hart clears the acknowledgement register and writes a performance counter value in the request register and a sequence number in the sequence number register. On observing  this request, PuC changes the performance state and writes the sequence number value of the original request in the Acknowledgement register. That completes the request.

PROBE_CPPC_REG service can be used to check if a particular CPPC register is implemented. The service READ_CPPC_REG can be used to read all implemented CPPC register values and  WRITE_CPPC_REG can be used to write the registers.

For extra debugging, Hart can send a GET_CPPC_PERF_POKE message to exclusively request PuC to process the pending CPPC requests, if any. 

For more information on CPPC, please refer to the ACPI Specification cite:[ACPI] and the CPPC Extension in the RISC-V SBI Specification cite:[SBI].

CPPC Fast-channel REQ-ACK Memory Entry per Hart:
[#table_cppc_fastchan_mem]
.CPPC Fast-Channel Memory Entry
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Word	| Description 				| Entity which writes the word
| 0	| Request Sequence Number Register	| AP
| 1	| Request Register			| AP
| 2	| Acknowledgement Register		| PuC
| 3	| Reserved				| None
|===

Below table lists the services in this group:
[#table_cppc_services]
.CPPC Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 				| Request Type
| 0x01		| CPPC_ENABLE_NOTIFICATION		| NORMAL_REQUEST
| 0x02		| CPPC_PROBE_REG			| NORMAL_REQUEST
| 0x03		| CPPC_READ_REG				| NORMAL_REQUEST
| 0x04		| CPPC_WRITE_REG			| NORMAL_REQUEST
| 0x05		| CPPC_GET_FAST_CHANNEL_ATTRIBUTES	| NORMAL_REQUEST
| 0x06		| CPPC_POKE_FAST_CHANNEL		| NORMAL_REQUEST
| 0x07		| CPPC_GET_HART_LIST			| NORMAL_REQUEST
|===

[#cppc-notifications]
==== CPPC
This service group does not support any event for notification.



==== Service: *CPPC_ENABLE_NOTIFICATION*
This service allows AP to subscribe to CPPC service group notifications.
Platform can optionally support notifications of events which might occur in
the platform. PuC can send these notification messages to AP if they are
implemented and AP has subscribed to these. Events supported are described
in <<cppc-notifications>>.

[#table_cppc_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_cppc_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===



==== Service: *CPPC_PROBE_REG*
Probe for CPPC register and get its length in bytes. If the register is not 
implemented, REG_LENGTH returned will be zero.

[#table_cppc_probereg_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| HART_ID	| uint32	| Hart ID
| 1	| REG_ID	| uint32	| Register ID (refer register ids in 
https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-cppc.adoc[SBI Spec])
|===

[#table_cppc_probereg_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and probing details returned.
! RPMI_ERROR_NOT_FOUND ! HART_ID not found
!===
- Other errors <<table_error_codes>>
| 1	| REG_LENGTH	| uint32	| Register Length
|===



==== Service: *CPPC_READ_REG*
Read CPPC register value

[#table_cppc_readreg_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| HART_ID	| uint32	| Hart ID
| 1	| REG_ID	| uint32	| Register ID (refer register ids in 
https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-cppc.adoc[SBI Spec])
|===

[#table_cppc_readreg_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! HART_ID not found
! RPMI_ERROR_INVALID_PARAMETER ! REG_ID is invalid or not implemented. AP must
probe the REG_ID before reading.
!===
- Other errors <<table_error_codes>>
| 1	| DATA_LOW	| uint32	| Lower `32 bits` of data
| 2	| DATA_HIGH	| uint32	| Upper `32 bits` of data
|===



==== Service: *CPPC_WRITE_REG*
Write a CPPC register

[#table_cppc_writereg_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| HART_ID	| uint32	| Hart ID
| 1	| REG_ID	| uint32	| Register ID (refer register ids in 
https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-cppc.adoc[SBI Spec])
| 2	| DATA_LOW	| uint32	| Lower `32 bits` of data
| 3	| DATA_HIGH	| uint32	| Upper `32 bits` of data
|===

[#table_cppc_writereg_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! HART_ID not found
! RPMI_ERROR_INVALID_PARAMETER ! REG_ID is invalid or not implemented. AP must
probe the REG_ID before reading.
!===
- Other errors <<table_error_codes>>
|===



==== Service: *CPPC_GET_FAST_CHANNEL_ATTRIBUTES*
This request retrieves attributes of the Fast-channel for a specified hart ID.
The physical address from this request shall be used to write the value of the https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/08_Processor_Configuration_and_Control/declaring-processors.html?highlight=desired-performance-register#desired-performance-register[CPPC Desired 
Performance Register].

[#table_cppc_getfastchanaddr_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| HART_ID	| uint32	| Hart ID
|===

[#table_cppc_getfastchanaddr_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! HART_ID not found
! RPMI_ERROR_NOT_SUPPORTED ! Fast-channel not implemented
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| 
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:3]	! _Reserved_
! [2:1]		! Doorbell Register Width

	0b00: 8 bits
	0b01: 16 bits
	0b10: 32 bits
	0b11: 64 bits
! [0]	!

	0b0: Doorbell not supported
	0b1: Doorbell supported
!===
| 2	|PHYS_ADDR_LOW	 | uint32	| Lower `32 bits` of physical address
| 3	|PHYS_ADDR_HIGH  | uint32	| Upper `32 bits` of physical address
| 4	|DB_ADDR_LOW	 | uint32	| Lower `32 bits` of doorbell address
| 5	|DB_ADDR_HIGH	 | uint32	| Upper `32 bits` of doorbell address
| 6	|DB_ID_LOW	 | uint32	| Lower `32 bits` of doorbell ID
| 7	|DB_ID_HIGH	 | uint32	| Upper `32 bits` of doorbell ID
|===



==== Service: *CPPC_POKE_FAST_CHANNEL*
Debug request message to poke the PuC FW to process the pending CPPC messages if
any.

[#table_cppc_pokefastchan_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
- NA

[#table_cppc_pokefastchan_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Fast-channel poked and service completed successfully.
!===
- Other errors <<table_error_codes>>
|===



==== Service: *CPPC_GET_HART_LIST*
This service gets the list of a hart with a specified hart ID start index.

[#table_cppc_gethartlist_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| START_INDEX	| uint32	| Starting index of Hart ID
|===

[#table_cppc_gethartlist_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===	
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_INVALID_PARAMETER ! Invalid START_INDEX
!===
- Other errors <<table_error_codes>>
| 1	| REMAINING	| uint32 | Remaining number of items to be returned
| 2	| RETURNED	| uint32 | Total number of items returned in this request.
| 3	| HART_ID[0]	| uint32 | Hart ID
| 4 	| HART_ID[1]	| uint32 | Hart ID
| N+2	| HART_ID[N-1]	| uint32 | Hart ID
|===