:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - DEVICE_POWER (SERVICEGROUP_ID: 0x0008)
This DEVICE_POWER service group provides messages to manage the power states of
a device power domain. This service group is used only for device power
management since system and CPU power management is handled by already defined
service groups such as SYSTEM_RESET, SYSTEM_SUSPEND and HART_STATE_MANAGEMENT.

A domain can consist of one device if its power states can be controlled
independently or it may also have multiple devices if they all share the same
power control lines and power states can only be changed collectively.
Each domain must support ON and OFF states along with custom power states which
are discoverable.  Domains may also have power states which may preserve the
context. The level of context preserved will depends on the level of power state.

Power states for domains will be discovered via supported hardware description
mechanisms where the values for ON and OFF are already fixed and known.
The power state encodes both the power state value and the context preserved or
lost information corresponding to that state.

The DEVICE_POWER services take a 32-bit integer identifier known as `DOMAIN_ID`
to specify the device power domain. These `DOMAIN_ID` identifiers are sequential
and start from `0`.

The following table lists the services in the DEVICE_POWER service group:

[#table_devpower_services]
.DEVICE_POWER Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| DPWR_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| DPWR_GET_NUM_DOMAINS
| NORMAL_REQUEST

| 0x03
| DPWR_GET_ATTRIBUTES
| NORMAL_REQUEST

| 0x04
| DPWR_SET_STATE
| NORMAL_REQUEST

| 0x05
| DPWR_GET_STATE
| NORMAL_REQUEST
|===

[#section-power-state]
==== Power State Format

The power state is represented as a 32-bit value. The following table shows the
encoding for the power state.

[#table_devpower_powerstate_data]
.Power State Encoding
[cols="2, 1, 5a", width=100%, align="center", options="header"]
|===
| Bit
| Name
| Description

| [31:17]
| RESERVED
| _Reserved_ and must be `0`.

| [16]
| CONTEXT
|
	0b1: Context is lost.
	0b0: Context is preserved.

| [15:0]
| VALUE
|
[cols="2,5", options="header"]
!===
! Value
! Description

! 0x0000
! On.

! 0x0001
! _Reserved_ and must be `0`.

! 0x0002
! _Reserved_ and must be `0`.

! 0x0003
! Off.

! 0x0004 - 0x0FFF
! _Reserved_ and must be `0`.

! 0x1000 - 0xFFFF
! Vendor specific states.
!===
|===

[#device-power-notifications]
==== Notifications
This service group does not support any events for notification.

==== Service: DPWR_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `DEVICE_POWER`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<device-power-notifications>>.

[#table_devpower_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state. +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable.
1: Enable.
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_devpower_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.
!===
- Other errors <<table_error_codes>>.

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state.
----
0: Notification is disabled.
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===


==== Service: DPWR_GET_NUM_DOMAINS (SERVICE_ID: 0x02)
This service is used to query the number of device power domains available which
can be controlled by the client. The number of domains returned may be less than
the actual number of domains present on the platform.

[#table_devpower_getdomains_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_devpower_getdomains_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="2,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

!===
- Other errors <<table_error_codes>>.

| 1
| NUM_DOMAINS
| uint32
| Number of device power domains.
|===


==== Service: DPWR_GET_ATTRIBUTES (SERVICE_ID: 0x03)
This service is used to query the attributes of a device power domain.

[#table_devpower_getattrs_request_data]
.Request Data
[cols="1, 3, 1, 6", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Device power domain ID.
|===

[#table_devpower_getattrs_response_data]
.Response Data
[cols="1, 3, 2, 6a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="8,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `DOMAIN_ID` is invalid.
!===
- Other errors <<table_error_codes>>.

| 1
| FLAGS
| uint32
| _Reserved_ and must be `0`.

| 2
| TRANSITION_LATENCY
| uint32
| Worst case transition latency of domain from one power state to another, in microseconds (us).

| 3:6
| DOMAIN_NAME
| uint8[16]
| Device power domain name, a NULL-terminated ASCII string up to 16-bytes.
|===


==== Service: DPWR_SET_STATE (SERVICE_ID: 0x04)
This service is used to change the power state of a device power domain.

[#table_devpower_setstate_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Device power domain ID.

| 1
| POWER_STATE
| uint32
| This field indicates the power state to which the power domain should
transition. The specific power states and their meanings may vary depending on
the implementation, but generally, they include values such as "ON", "OFF"
and vendor specific power state. Refer <<section-power-state>>
for more details.
|===

[#table_devpower_setstate_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `DOMAIN_ID` or `POWER_STATE` is invalid.

! RPMI_ERR_DENIED
! Denied due to no permission.

! RPMI_ERR_HW_FAULT
! Failed due to hardware error.
!===
- Other errors <<table_error_codes>>.
|===

==== Service: DPWR_GET_STATE (SERVICE_ID: 0x05)
This service is used to get the current power state of a device power domain.

[#table_devpower_getstate_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| DOMAIN_ID
| uint32
| Device power domain ID.
|===

[#table_devpower_getstate_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `DOMAIN_ID` is invalid.

!===
- Other errors <<table_error_codes>>.

| 1
| POWER_STATE
| uint32
| This field indicates the current power state of the specified domain. The
power state can be one of several predefined values, such as ON, OFF, or vendor
specific implementation. Refer <<section-power-state>>
for more details.
|===
