:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - *CLOCK* (servicegroup_id: 0x00007)
This service group is for the management of system clocks. Services defined in 
this group are used to enable or disable clocks, and to set/get clock rates.

Each clock in the system is identified by the clock ID, which is an integer
identifier assigned to each clock. The mapping of CLOCK_ID and clock is known
to both the AP and the Platform Microcontroller. Clock ID identifiers are
sequential and starting from `0`.

The device or the group of devices sharing the same clock source form a
single clock domain, which is identified by the CLOCK_ID. Any change to the
clock source affects the entire domain which may contain multiple devices.

The topology of the devices and the clock source is dependent on how the system
is designed and implementation specific. The OS can discover this topology
through supported hardware description mechanisms.

*Clock Rate Format*::
Each clock rate is a tuple of two `32 bits` values `(uint32, uint32)` represented
as `(clock_rate_low, clock_rate_high)` and packed in the same order where
`clock_rate_low` is at the lower index than the `clock_rate_high`.

Below table lists the services in this group:
[#table_clock_services]
.CLOCK Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| CLK_ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| CLK_GET_NUM_CLOCKS		| NORMAL_REQUEST
| 0x03		| CLK_GET_ATTRIBUTES		| NORMAL_REQUEST
| 0x04		| CLK_GET_SUPPORTED_RATES	| NORMAL_REQUEST
| 0x05		| CLK_SET_CONFIG		| NORMAL_REQUEST
| 0x06		| CLK_GET_CONFIG		| NORMAL_REQUEST
| 0x07		| CLK_SET_RATE			| NORMAL_REQUEST
| 0x08		| CLK_GET_RATE			| NORMAL_REQUEST
|===

[#clock-notifications]
==== Notifications
This service group does not support any event for notification

==== Service: *CLK_ENABLE_NOTIFICATION*
This service allows the AP to subscribe to CLOCK service group notifications.
The platform can optionally support notifications of events which might occur in
the platform. The PuC can send these notification messages to AP if they are
implemented and the AP has subscribed to these. The supported events are described
in <<clock-notifications>>.
 
[#table_clock_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_clock_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *CLK_GET_NUM_CLOCKS*
This service is used to query the number of clocks available in the system.
All supported clocks in the system are designated by an integer identifier
called CLOCK_ID. CLOCK_ID are sequential starting from `0`.

[#table_clock_getnumclocks_request_data]
.Request Data
- NA

[#table_clock_getnumclocks_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
!===
- Other errors <<table_error_codes>>
| 1	|	NUM_CLOCKS	| uint32 	| Number of Clocks
|===

==== Service: *CLK_GET_ATTRIBUTES*
This service provides detailed attributes of a clock, including its name,
represented as a 16-byte array of ASCII strings. It also specifies the
transition latency, which denotes the maximum time for the clock to stabilize
after a configuration change. Moreover, it indicates the number of clock rates
supported by the requested clock. The FLAGS field encodes the clock formats
supported by the clock.

Currently supported clock formats include `discrete` format, represented as an
array where each value represents a clock rate, and `linear` format represented
as `(min_Hz, max_Hz, step_Hz)`. Additional clock formats may be supported in
the future, as needed.

[#table_clock_getattrs_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
|===

[#table_clock_getattrs_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="4,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Clock not found
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| 
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:30]	! CLOCK_FORMAT

	0b00: Discrete Format
	Each element in the CLOCK_RATE array is a supported discrete clock rate value packed in ascending order. Each rate is in Hertz.

	0b01: Linear Range
	The CLOCK_RATE array contains the triplet (min_Hz, max_Hz, step_Hz). 
	Each item in the triplet is a clock rate value.
	CLOCK_RATE[0] = min_Hz  (lowest physical rate that the clock can synthesize)
	CLOCK_RATE[1] = max_Hz   (highest physical rate that the clock can synthesize)
	CLOCK_RATE[2] = step_Hz   (Step between two successive rates)
! [29:0]	! _Reserved_
!===
| 2	|NUM_RATESS	 	| uint32	| Number of clock rates of type depending on CLOCK_FORMAT.
| 3	| TRANSITION_LATENCY	| uint32	| Transition latency, in microseconds (us)
| 4:7	| CLOCK_NAME		| uint8[16]	| Clock name
|===

==== Service: *CLK_GET_SUPPORTED_RATES*
Each domain may support multiple clock rate values which are allowed by the 
domain to operate. Message can also pass the `CLOCK_RATE_INDEX` which is the index
to the first rate value to be described in the return rate array. If all 
supported rate values are required then this index value can be `0`. 

If the CLOCK_FORMAT is discrete then the clock rate in the received data is an 
array of supported discrete rate values packed in ascending order starting from
the lower index in the CLOCK_RATE field. If the CLOCK_FORMAT is a linear range, 
then the CLOCK_RATE array contains a triplet of `(min_Hz, max_Hz, step_Hz)` where
each item in the triplet is a clock rate value. 

Total words required for the number of clock rates according to the format in 
one message cannot exceed the total words available in one message DATA field. 
If they exceed then the PuC will return the number of clock rates which can be
accommodated in one message and set the REMAINING field accordingly. The AP,
when REMAINING field is not `0` must call this service again with appropriate
CLOCK_RATE_INDEX set to get the remaining clock rates. It's possible that 
multiple service calls may be required to get all the clock rates. 
In case the CLOCK_FORMAT is a linear range the RETURNED field will be set to `3`.

[#table_clock_getsupprates_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
| 1	| CLOCK_RATE_INDEX | uint32	| Clock rate index
|===

[#table_clock_getsupprates_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="7,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! CLOCK_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! CLOCK_RATE_INDEX is not in valid range.
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| _Reserved_ and must be `0`.
| 2	| REMAINING	| uint32	| Remaining number of clock rates.
| 3	| RETURNED	| uint32	| Number of clock rates returned in this request.
| 4	| CLOCK_RATE[0]	| (uint32, uint32) | Clock rate value.
| 5	| CLOCK_RATE[1]	| (uint32, uint32) | Clock rate value.
| ...	| CLOCK_RATE[N-1] | (uint32, uint32) | Clock rate value.
|===

==== Service: *CLK_SET_CONFIG*
Set clock config, enable or disable the clock.

[#table_clock_setconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
| 1	| CONFIG	| uint32	| Clock config
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:1]	! _Reserved_
! [0]		! 

	0b0: Disable clock

	0b1: Enable clock
!===
|===

[#table_clock_setconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! CLOCK_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! CONFIG is not supported by the clock.
!===
- Other errors <<table_error_codes>>
|===


==== Service: *CLK_GET_CONFIG*
Get the current status of a clock, if it's enabled or disabled.

[#table_clock_getconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
|===

[#table_clock_getconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! CLOCK_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| CONFIG	| uint32	| Clock config
[cols="2,5a"]
!===
! *Value* 	!  *Description*
! 0x0		! Disabled 
! 0x1		! Enabled
!===
|===

==== Service: *CLK_SET_RATE*
Set clock rate.

[#table_clock_setrate_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
| 1	| FLAGS		| uint32	|
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:30]	! Clock rate roundup/rounddown

	0b00: Round down

	0b01: Round up

	0b10: Auto. Platform autonomously choose rate closest to the requested
	rate.

! [29:0]	! _Reserved_ 
!===
| 2	| CLOCK_RATE_LOW	| uint32	| Lower 32 bits of the clock rate in Hertz.
| 3	| CLOCK_RATE_HIGH	| uint32	| Upper 32 bits of the clock rate in Hertz.
|===

[#table_clock_setrate_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="7,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! CLOCK_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! Clock rate is not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *CLK_GET_RATE*
Get the current clock rate value.

[#table_clock_getrate_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| CLOCK_ID	| uint32	| Clock ID
|===

[#table_clock_getrate_response_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! CLOCK_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| CLOCK_RATE_LOW	| uint32	| Lower 32 bits of the clock rate in Hertz.
| 2	| CLOCK_RATE_HIGH	| uint32	| Upper 32 bits of the clock rate in Hertz.
|===
