
===  Service Group - *VOLTAGE* (servicegroup_id: 0x00006)
The system can be classified into multiple domains for voltage control.
Each domain is the logical grouping of one or more devices powered by a single
voltage source. Actions associated with messages within each domain control the
voltage source, thereby influencing either the individual device or the collective
group of devices sharing the same voltage source.
Each domain is identified by `DOMAIN_ID` which is a `32 bits` integer starting from `0`.

Below table lists the services in this group:
[#table_voltage_services]
.Voltage Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| VOLT_ENABLE_NOTIFICATION	| NORMAL_REQUEST
| 0x02		| VOLT_GET_NUM_DOMAINS		| NORMAL_REQUEST
| 0x03		| VOLT_GET_ATTRIBUTES		| NORMAL_REQUEST
| 0x04		| VOLT_GET_SUPPORTED_LEVELS	| NORMAL_REQUEST
| 0x05		| VOLT_SET_CONFIG		| NORMAL_REQUEST
| 0x06		| VOLT_GET_CONFIG		| NORMAL_REQUEST
| 0x07		| VOLT_SET_LEVEL		| NORMAL_REQUEST
| 0x08		| VOLT_GET_LEVEL		| NORMAL_REQUEST
|===

==== Voltage Notifications
This service group does not support any event for notification.

==== Service: *VOLT_ENABLE_NOTIFICATION*
This service allows the AP to subscribe to voltage service group notifications.
The platform can optionally support notifications of events which might occur in the platform.
The PuC can send these notification messages to the AP if they are implemented
and the AP has subscribed to them. The supported events are described above in Voltage Notifications.
 

[#table_voltage_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| EVENT_ID	| uint32	| Event to be subscribed for 
notification.
|===

[#table_voltage_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Notifications are subscribed successfully.
! RPMI_ERROR_NOT_FOUND ! EVENT_ID is not supported or invalid.
! RPMI_ERROR_NOT_SUPPORTED ! Notifications not supported.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *VOLT_GET_NUM_DOMAINS*
Request for the number of voltage domains available in the system.

[#table_voltage_getnumdomains_request_data]
.Request Data
- NA

[#table_voltage_getnumdomains_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and voltage domains returned
as NUM_DOMAINS.
!===
- Other errors <<table_error_codes>>
| 1	|	NUM_DOMAINS 	| uint32 	| Number of voltage domains
|===

==== Service: *VOLT_GET_ATTRIBUTES*
Each domain may support multiple voltage levels, which are permitted by the domain
for operation. For each domain, this message returns a domain name, represented as
a NULL-terminated ASCII string of 16 bytes. The number of levels indicates the total
count of voltage levels supported within a voltage domain. Transition latency
denotes the maximum time required for the voltage to stabilize upon a change in
the regulator. Depending on the hardware, voltage levels can be of various formats,
and the current service supports Simple-linear, Multi-linear, and Discrete range
formats. Additional voltage formats can be accommodated in the future if required.

[#table_voltage_getdomainattrs_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainattrs_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| 
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:30]	! VOLTAGE_FORMAT

	0b00: Fixed voltage

	0b01: Simple-linear range containing single triplet (min_uV, max_uV, step_uV).
	
	0b10: Multi-linear range containing multiple linear ranges of type `0x1` where each range contains (min_uV, min_sel, max_sel, step_uV).
	
	0b11: Discrete range.
! [29:1]	! _Reserved_
! [0]		! ALWAYS_ON

	0b0: Voltage domain can be enabled/disabled.

	0b1: Voltage domain is always-on, voltage value can be changed in the supported voltage range.
!===
| 2	|NUM_LEVELS	 | uint32	| Number of voltage levels supported by 
domain. Some values are dependent on the VOLTAGE_FORMAT.
[cols="2,5a"]
!===
! *Value* 	!  *Description*
! 1		! When VOLTAGE_FORMAT=`0x0`
! 3		! When VOLTAGE_FORMAT=`0x1`
! N		! When VOLTAGE_FORMAT=`0x2` or `0x3`. Based on the format here
each item can be a single voltage value or tuple of values. Check the VOLTAGE_FORMAT
field in FLAGS.
!===
| 3	| TRANSITION_LATENCY	| uint32	| Transition latency, in microsecond (us).
| 4:7	| VOLTAGE_DOMAIN_NAME	| uint8[16]	| Voltage domain name, a NULL-terminated ASCII string up to 16-bytes.
|===

==== Service: *VOLT_GET_SUPPORTED_LEVELS*
Each domain may support multiple voltage levels which are allowed by the domain 
to operate.
Depending on the hardware, the voltage levels can be either discrete or stepwise range.
In a discrete voltage range, the voltages will be arranged in sequence, starting
from the lowest voltage value at the lowest index and increasing sequentially to
higher voltage levels. The number of voltage levels returned depends on the
format of the voltage level.

The total number of words required to represent the voltage levels in one message
cannot exceed the total words available in one message DATA field. If the number
of levels exceeds this limit, the PuC will return the maximum number of levels
that can be accommodated in one message and adjust the REMAINING field accordingly.
When the REMAINING field is not zero, the AP must make subsequent service calls
with the appropriate VOLTAGE_LEVEL_INDEX set to retrieve the remaining voltage
levels. It is possible that multiple service calls may be necessary to retrieve
all the voltage levels.

[#table_voltage_getdomainlevels_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| VOLTAGE_LEVEL_INDEX | uint32	| Voltage level index
|===

[#table_voltage_getdomainlevels_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="7,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and voltage levels returned.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! VOLTAGE_LEVEL_INDEX is not valid
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| _Reserved_ and must be `0`.
| 2	| REMAINING	| uint32	| Remaining number of levels.
| 3	| RETURNED	| uint32	| Number of levels returned in this request.
| 4	| VOLTAGE[0]	| int32	| Voltage array where each entry in the
array is a voltage level in microvolts (uV).

N is specified by the VOLT_GET_ATTRIBUTES.NUM_LEVELS. Voltage represented in 
microvolt (uV).

If the bits in VOLT_GET_ATTRIBUTES.FLAGS[31:30] are set to `0` (Fixed voltage), VOLTAGE[0]
contains a fixed voltage level in the array. +
`VOLTAGE[0]: volt_uV`

If the bits in VOLT_GET_ATTRIBUTES.FLAGS[31:30] are set to `1` (Simple-linear), it means that
the voltage array contains three entries as below: +
`VOLTAGE[0]: min_uV +
VOLTAGE[1]: max_uV +
VOLTAGE[2]: step_uV`
 
If the bits in VOLT_GET_ATTRIBUTES.FLAGS[31:30] are set to `2` (Multi-linear), it indicates
that the voltage array contains multiple groups of four entries. Each group 
represent a linear voltage range and consists of the following entries: +
`VOLTAGE[0] = min_uV +
VOLTAGE[1] = min_sel +
VOLTAGE[2] = max_sel +
VOLTAGE[3] = step_uV`

If the bits in  VOLT_GET_ATTRIBUTES.FLAGS[31:30] are set to 3 (Discrete), it means that
the entry array contains discrete voltage levels listed in ascending numeric 
order (_Low index represents minimum voltage level, and high index represents
maximum voltage level supported_). +
`VOLTAGE[0]: Voltage0 +
VOLTAGE[1]: Voltage1 +
VOLTAGE[2]: Voltage2 +
VOLTAGE[N - 1]: Voltage(N – 1)`
| 5	| VOLTAGE[1]	| int32	|
| ...	| VOLTAGE[N-1]	| int32	|
|===

==== Service: *VOLT_SET_CONFIG*
Set voltage config message enable or disable any voltage domain. Enabling the voltage
means applying the domain with the voltage level to operate normally. The AP can
enable the voltage to any domain without knowing the actual voltage levels. 
Disabling the voltage level means disabling the voltage supply to the domain.

CONFIG field encodes these discrete settings which do not require AP to know 
the voltage level
[#table_voltage_setdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| CONFIG	| uint32	| Voltage domain config
[cols="2,5a"]
!===
! *Bits* 	!  *Description*
! [31:1]	! _Reserved_
! [0]		! 

	0b0: Disable voltage for domain

	0b1: Enable voltage for domain
!===
|===

[#table_voltage_setdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! Voltage config is not supported by the
specified voltage domain.
!===
- Other errors <<table_error_codes>>
|===

==== Service: *VOLT_GET_CONFIG*
Get voltage config message request for the configuration of the voltage domain 
currently set.
[#table_voltage_getdomainconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| CONFIG	| uint32	| Voltage domain config
[cols="2,5a"]
!===
! *Value* 	!  *Description*
! 0x0		! Disabled 
! 0x1		! Enabled
!===
|===


==== Service: *VOLT_SET_LEVEL*
Set the voltage level in microvolts (uV) of a voltage domain.

[#table_voltage_setdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
| 1	| VOLTAGE_LEVEL	| int32		| Voltage level, in microvolts (uV).
|===

[#table_voltage_setdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="6,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
! RPMI_ERROR_INVALID_PARAMETER	! Voltage level is not supported by specified
voltage domain.
!===
- Other errors <<table_error_codes>>
|===


==== Service: *VOLT_GET_LEVEL*
Get the current voltage level in microvolts (uV) of a voltage domain.

[#table_voltage_getdomainlevel_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| DOMAIN_ID	| uint32	| Voltage Domain ID
|===

[#table_voltage_getdomainlevel_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="5,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully.
! RPMI_ERROR_NOT_FOUND ! Voltage DOMAIN_ID not found.
!===
- Other errors <<table_error_codes>>
| 1	| VOLTAGE_LEVEL	| int32	| Voltage level, in microvolts (uV).
|===
