:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - BOOTSTATUS (SERVICEGROUP_ID: 0x000E)
This service group defines services used by platform microcontroller
to collect the boot status codes defined by https://uefi.org/specs/PI/1.9/V3_Status_Codes.html[UEFI Platform Initialization specification]. For now theres no way for platform controller to inform boot status code data.
Once this data is collected by platform controller it can then be relayed to consumers like BMC, LCD display etc.

The following table lists the services in the BOOTSTATUS service group:

[#table_bootstatus_services]
.BOOTSTATUS Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| BOOTSTATUS_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| BOOTSTATUS_SET_STATUS
| NORMAL_REQUEST

|===

[#section-bootstatus-types]
==== BOOT status Types

[#table_bootstatus_type]
.Boot status Types
[cols="2, 3a", width=100%, align="center", options="header"]
|===
| Type
| Value (32-bit)

| 0x1
| Progress code

| 0x2
| Error code

| 0x3
| Debug code
|===

[#bootstatus-notifications]
==== Notifications
This service group does not support any events for notification.

==== Service: BOOTSTATUS_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `BOOTSTATUS`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<bootstatus-notifications>>.

[#table_bootstatus_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| WORD
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state. +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable.
1: Enable.
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_bootstatus_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| WORD
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification for the `EVENT_ID` is not supported.
!===
- Other errors <<table_error_codes>>.

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state.
----
0: Notification is disabled.
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===

==== Service: BOOTSTATUS_SET_STATUS (SERVICE_ID: 0x02)
This service is used to set the boot status

[#table_bootstat_getstatus_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| WORD
| Name
| Type
| Description

| 0
| BOOTSTATUS_TYPE
| uint32
| BOOTSTATUS type. +
Refer <<section-bootstatus-types>> for more details.

| 1
| DATA_LENGTH
| uint32
| Number of uint32 WORDs of Boot status data returned

| 2
| DATA[]
| uint32[]
| Boot status data

|===

[#table_bootstatus_getstatus_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| WORD
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Boot status set successfully.
!===
- Other errors <<table_error_codes>>.
|===

