:path: src/
:imagesdir: ../images

ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ./../
endif::rootpath[]

===  Service Group - CLOCK (SERVICEGROUP_ID: 0x0008)
This service group is used to manage system clocks. Services defined in this group
are used to enable or disable clocks, set or get clock rates, etc.

Each clock in the system is identified by a clock ID, which is a 32-bit integer
identifier assigned to each clock. The mapping of CLOCK_ID to clock is known to
both the application processor and the platform microcontroller.
Clock IDs are sequential and start from `0`.

A device or a group of devices sharing the same clock source form a single clock
domain identified by the CLOCK_ID. Any change to the clock source affects the
entire domain, which may include multiple devices.

The topology of the devices and the clock source depends on the system design and
is implementation specific. The operating system can discover this topology through
supported hardware description mechanisms.

The following table lists the services in the CLOCK service group:

[#table_clock_services]
.CLOCK Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID
| Service Name
| Request Type

| 0x01
| CLK_ENABLE_NOTIFICATION
| NORMAL_REQUEST

| 0x02
| CLK_GET_NUM_CLOCKS
| NORMAL_REQUEST

| 0x03
| CLK_GET_ATTRIBUTES
| NORMAL_REQUEST

| 0x04
| CLK_GET_SUPPORTED_RATES
| NORMAL_REQUEST

| 0x05
| CLK_SET_CONFIG
| NORMAL_REQUEST

| 0x06
| CLK_GET_CONFIG
| NORMAL_REQUEST

| 0x07
| CLK_SET_RATE
| NORMAL_REQUEST

| 0x08
| CLK_GET_RATE
| NORMAL_REQUEST
|===

[#clock-rate-format-section]
==== Clock Rate Format
Each clock rate is a array of two 32-bit values `(uint32, uint32)` represented
as `(clock_rate_low, clock_rate_high)` and packed in the same order where
`clock_rate_low` is at the lower index than the `clock_rate_high`.

===== Discrete Format
A set of discrete clock rates arranged in a sequence, starting from the
lowest value at the lowest index and increasing sequentially to higher clock
rate. The following table shows the structure of the discrete clock rate format.

```c
[clock_rate1, clock_rate2, clock_rate3, ... , clock_rateN]

where:
clock_rate1 < clock_rate2 < clock_rate3 < ... < clock_rateN
```

[#clock-rate-format-discrete]
.Discrete Clock Format Structure
[cols="1,2,5" width=100%, align="center", options="header"]
|===
| Word
| Name
| Description

| 0
| CLOCK_RATE_LOW
| Lower 32-bit clock rate in Hz.

| 1
| CLOCK_RATE_HIGH
| Upper 32-bit clock rate in Hz.
|===

[#clock-rate-format-linear]
===== Linear Range Format
A linear range of clock rates represented by minimum and maximum clock rate and
a constant step size. The following table shows the fixed structure of the linear
range format for clock rates.

```c
[clock_rate_min, clock_rate_max, clock_step]
```

.Linear Range Format Structure
[cols="1,3,5" width=100%, align="center", options="header"]
|===
| Word
| Name
| Description

| 0
| CLOCK_MIN_RATE_LOW
| Lower 32-bit of the lowest clock rate in Hz.

| 1
| CLOCK_MIN_RATE_HIGH
| Upper 32-bit of the lowest clock rate in Hz.

| 2
| CLOCK_MAX_RATE_LOW
| Lower 32-bit of the highest clock rate in Hz.

| 3
| CLOCK_MAX_RATE_HIGH
| Upper 32-bit of the highest clock rate in Hz.

| 4
| CLOCK_STEP_LOW
| Lower 32-bit of the step between two successive rates in Hz.

| 5
| CLOCK_STEP_HIGH
| Upper 32-bit of the step between two successive rates in Hz.
|===

A clock may also support clock rates which can be represented by multiple
linear ranges. For example,
```c
[clock_rate_min1, clock_rate_max1, clock_rate_step1],
[clock_rate_min2, clock_rate_max2, clock_rate_step2],
 ...,
[clock_rate_minN, clock_rate_maxN, clock_rate_stepN]
```
The linear ranges must be packed sequentially such that
`clock_rate_max1 < clock_rate_min2`, `clock_rate_max2 < clock_rate_min3` and
so on.

[#clock-notifications]
==== Notifications
This service group does not support any events for notification.

==== Service: CLK_ENABLE_NOTIFICATION (SERVICE_ID: 0x01)
This service allows the application processor to subscribe to `CLOCK`
service group notifications. The platform may optionally support notifications
for events that may occur. The platform microcontroller can send these
notification messages to the application processor if they are implemented and
the application processor has subscribed to them. The supported events are
described in <<clock-notifications>>.

[#table_clock_ennotification_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| EVENT_ID
| uint32
| The event to be subscribed for notification.

| 1
| REQ_STATE
| uint32
| Requested event notification state. +
Change or query the current state of `EVENT_ID` notification.
----
0: Disable.
1: Enable.
2: Return current state.
----
Any other values of `REQ_STATE` field other than the defined ones are reserved
for future use.
|===

[#table_clock_ennotification_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5a", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Event is subscribed successfully.

! RPMI_ERR_INVALID_PARAM
! `EVENT_ID` or `REQ_STATE` is invalid.

! RPMI_ERR_NOT_SUPPORTED
! Notification is not supported.
!===
- Other errors <<table_error_codes>>

| 1
| CURRENT_STATE
| uint32
| Current `EVENT_ID` notification state.
----
0: Notification is disabled.
1: Notification is enabled.
----
In case of `REQ_STATE = 0` or `1`, the `CURRENT_STATE` will return the requested
state. +
In case of an error, the value of `CURRENT_STATE` is unspecified.
|===


==== Service: CLK_GET_NUM_CLOCKS (SERVICE_ID: 0x02)
This service is used to query the number of clocks available in the system.
All supported clocks in the system are designated by an integer identifier
called `CLOCK_ID`.

[#table_clock_getnumclocks_request_data]
.Request Data
[cols="1", width=100%, align="center", options="header"]
|===
| NA
|===

[#table_clock_getnumclocks_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="2,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

!===
- Other errors <<table_error_codes>>.

| 1
| NUM_CLOCKS
| uint32
| Number of clocks.
|===

==== Service: CLK_GET_ATTRIBUTES (SERVICE_ID: 0x03)
This service provides detailed attributes of a clock, including its name,
represented as a 16-byte array of ASCII strings. It also specifies the
transition latency, which denotes the maximum time for the clock to stabilize
after a configuration change.
The `FLAGS` field encodes the clock formats supported by the clock. When the
format is of the discrete type, the `NUM_RATES` field returns the number of discrete
clock rates supported by the clock. In the case of linear range format the `NUM_RATES`
will return the number of linear ranges supported.

[#table_clock_getattrs_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.
|===

[#table_clock_getattrs_response_data]
.Response Data
[cols="1, 3, 2, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="7,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` is invalid.

!===
- Other errors <<table_error_codes>>.

| 1
| FLAGS
| uint32
|
[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:2]
! _Reserved_ and must be `0`.

! [1:0]
! Clock format.

Refer to <<clock-rate-format-section>> for more details.
----
0b00: Discrete format.
0b01: Linear range format.
0b10 - 0b11: Reserved.
----

!===

| 2
| NUM_RATES
| uint32
| The number of discrete clock rates if the format is of discrete type, or the
  number of linear ranges if the format is linear range.

| 3
| TRANSITION_LATENCY
| uint32
| Transition latency, in microseconds (us).

| 4:7
| CLOCK_NAME
| uint8[16]
| Clock name, a NULL-terminated ASCII string up to 16-bytes.
|===

==== Service: CLK_GET_SUPPORTED_RATES (SERVICE_ID: 0x04)
This service is used to get the supported clock rates. The clock rate data returned
by this service depends on the format supported by the clock.

If the format is discrete, the message can pass the `CLOCK_RATE_INDEX` which is
the index to the first rate value to be described in the returned rate array. If all
supported rate values are required then this index value can be `0`. Similarly, if
the format is linear range, then the `CLOCK_RATE_INDEX` is the index of the first linear
range to be described in the returned clock rate linear ranges. If all the supported
linear ranges are needed then this index value can be `0`.

The total number of words required for the number of discrete clock rates or
linear ranges according to the format in one message must not exceed the total
words available in a message DATA field. If the format is linear range and a clock
supports multiple linear ranges, then only complete linear ranges must be returned
as per the data format of the linear range described in <<clock-rate-format-linear>>.

If the total number of words required to store all supported discrete clock rates
or the linear ranges exceed the available words in message DATA field then `REMAINING`
and `RETURNED` must be set accordingly. In such condition, if the format is
discrete, the platform microcontroller will return the discrete clock rates which
can be accommodated in one message and set the `RETURNED` field to number of
discrete clock rates returned and `REMAINING` field is set to the remaining number
of discrete clock rates. Similarly if the format is linear, the linear ranges
which can be accommodated in one message are returned with `RETURNED` field set
to the number of linear ranges returned and `REMAINING` field is set to the
remaining number of linear ranges.

The application processor, when `REMAINING` field is not `0` must
call this service again with appropriate `CLOCK_RATE_INDEX` set to get the
remaining discrete clock rates or linear ranges.

[#table_clock_getsupprates_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.

| 1
| CLOCK_RATE_INDEX
| uint32
| Clock rate index.
|===

[#table_clock_getsupprates_response_data]
.Response Data
[cols="1, 3, 2, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` or `CLOCK_RATE_INDEX` is invalid.

!===
- Other errors <<table_error_codes>>.

| 1
| FLAGS
| uint32
| _Reserved_ and must be `0`.

| 2
| REMAINING
| uint32
| The remaining number of discrete clock rates if the format is discrete type, or
the remaining number of linear ranges if the format is linear range.

| 3
| RETURNED
| uint32
| The number of discrete clock rates returned if the format is discrete type, or
the number of linear ranges returned if the format is linear range.

| 4
| CLOCK_RATE[ ]
| uint32[2]
| Clock rates. +
The clock rate data structure and its packing is according to the supported format.
Refer to <<clock-rate-format-section>> for more details.
|===

==== Service: CLK_SET_CONFIG (SERVICE_ID: 0x05)
This service is used to configure a clock domain.

[#table_clock_setconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.

| 1
| CONFIG
| uint32
| Clock config.

[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:1]
! _Reserved_ and must be `0`.

! [0]
! Clock control.

	0b0: Disable clock.
	0b1: Enable clock.
!===
|===

[#table_clock_setconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` or `CONFIG` is invalid.

!===
- Other errors <<table_error_codes>>.
|===


==== Service: CLK_GET_CONFIG (SERVICE_ID: 0x06)
This service is used to get the configuration of a clock domain.

[#table_clock_getconfig_request_data]
.Request Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.
|===

[#table_clock_getconfig_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` is invalid.

!===
- Other errors <<table_error_codes>>

| 1
| CONFIG
| uint32
| Clock config.

[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:1]
! _Reserved_ and must be `0`.

! [0]
! Clock state.

	0b0: Clock is disabled.
	0b1: Clock is enabled.
!===
|===

==== Service: CLK_SET_RATE (SERVICE_ID: 0x07)
This service is used to set the clock rate of a specific clock.

[#table_clock_setrate_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.

| 1
| FLAGS
| uint32
|
[cols="2,5a", options="header"]
!===
! Bits
! Description

! [31:2]
! _Reserved_ and must be `0`.

! [1:0]
! Clock rate rounding mode.
----
0b00: Round down.
0b01: Round up.
0b10: Auto.
0b11: Reserved.

In Auto mode the platform can autonomously chooses a supported rate closest to the requested rate.
----
!===

| 2
| CLOCK_RATE_LOW
| uint32
| Lower 32-bit of the clock rate in Hertz.

| 3
| CLOCK_RATE_HIGH
| uint32
| Upper 32-bit of the clock rate in Hertz.
|===

[#table_clock_setrate_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="6,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` or clock rate is invalid or the flags passed are invalid or reserved.

!===
- Other errors <<table_error_codes>>.
|===

==== Service: CLK_GET_RATE (SERVICE_ID: 0x08)
This service is used to get the current clock rate.

[#table_clock_getrate_request_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| CLOCK_ID
| uint32
| Clock ID.
|===

[#table_clock_getrate_response_data]
.Request Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word
| Name
| Type
| Description

| 0
| STATUS
| int32
| Return error code.

[cols="5,5", options="header"]
!===
! Error Code
! Description

! RPMI_SUCCESS
! Service completed successfully.

! RPMI_ERR_INVALID_PARAM
! `CLOCK_ID` is invalid.

!===
- Other errors <<table_error_codes>>.

| 1
| CLOCK_RATE_LOW
| uint32
| Lower 32-bit of the clock rate in Hertz.

| 2
| CLOCK_RATE_HIGH
| uint32
| Upper 32-bit of the clock rate in Hertz.
|===
